package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "traveldb")
public class Address implements java.io.Serializable {

	private Integer addressId;
	private Shop shop;
	private String street;
	private String city;
	private String postalCode;
	private String fullAddress;
	private String quarter;
	private double lat;
	private double laung;
	private String phone;

	public Address() {
	}

	public Address(Shop shop, String street, String city, String postalCode, String fullAddress, double lat,
			double laung, String phone) {
		this.shop = shop;
		this.street = street;
		this.city = city;
		this.postalCode = postalCode;
		this.fullAddress = fullAddress;
		this.lat = lat;
		this.laung = laung;
		this.phone = phone;
	}

	public Address(Shop shop, String street, String city, String postalCode, String fullAddress, String quarter,
			double lat, double laung, String phone) {
		this.shop = shop;
		this.street = street;
		this.city = city;
		this.postalCode = postalCode;
		this.fullAddress = fullAddress;
		this.quarter = quarter;
		this.lat = lat;
		this.laung = laung;
		this.phone = phone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "shop_id", nullable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@Column(name = "street", nullable = false, length = 100)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "city", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "postal_code", nullable = false, length = 20)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "full_address", nullable = false, length = 5000)
	public String getFullAddress() {
		return this.fullAddress;
	}

	public void setFullAddress(String fullAddress) {
		this.fullAddress = fullAddress;
	}

	@Column(name = "quarter", length = 200)
	public String getQuarter() {
		return this.quarter;
	}

	public void setQuarter(String quarter) {
		this.quarter = quarter;
	}

	@Column(name = "lat", nullable = false, precision = 22, scale = 0)
	public double getLat() {
		return this.lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	@Column(name = "laung", nullable = false, precision = 22, scale = 0)
	public double getLaung() {
		return this.laung;
	}

	public void setLaung(double laung) {
		this.laung = laung;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
