package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Day generated by hbm2java
 */
@Entity
@Table(name = "day", catalog = "traveldb")
public class Day implements java.io.Serializable {

	private Integer dayId;
	private String dayName;
	private Set<TimeTable> timeTables = new HashSet<TimeTable>(0);

	public Day() {
	}

	public Day(String dayName) {
		this.dayName = dayName;
	}

	public Day(String dayName, Set<TimeTable> timeTables) {
		this.dayName = dayName;
		this.timeTables = timeTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "day_id", unique = true, nullable = false)
	public Integer getDayId() {
		return this.dayId;
	}

	public void setDayId(Integer dayId) {
		this.dayId = dayId;
	}

	@Column(name = "day_name", nullable = false, length = 50)
	public String getDayName() {
		return this.dayName;
	}

	public void setDayName(String dayName) {
		this.dayName = dayName;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "day")
	public Set<TimeTable> getTimeTables() {
		return this.timeTables;
	}

	public void setTimeTables(Set<TimeTable> timeTables) {
		this.timeTables = timeTables;
	}

}
