package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ingredient generated by hbm2java
 */
@Entity
@Table(name = "ingredient", catalog = "traveldb")
public class Ingredient implements java.io.Serializable {

	private Integer ingredientId;
	private String name;
	private Set<IngredientJoinItemResturant> ingredientJoinItemResturants = new HashSet<IngredientJoinItemResturant>(0);

	public Ingredient() {
	}

	public Ingredient(String name) {
		this.name = name;
	}

	public Ingredient(String name, Set<IngredientJoinItemResturant> ingredientJoinItemResturants) {
		this.name = name;
		this.ingredientJoinItemResturants = ingredientJoinItemResturants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ingredient_id", unique = true, nullable = false)
	public Integer getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(Integer ingredientId) {
		this.ingredientId = ingredientId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ingredient")
	public Set<IngredientJoinItemResturant> getIngredientJoinItemResturants() {
		return this.ingredientJoinItemResturants;
	}

	public void setIngredientJoinItemResturants(Set<IngredientJoinItemResturant> ingredientJoinItemResturants) {
		this.ingredientJoinItemResturants = ingredientJoinItemResturants;
	}

}
