package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IngredientJoinItemResturant generated by hbm2java
 */
@Entity
@Table(name = "ingredient_join_item_resturant", catalog = "traveldb")
public class IngredientJoinItemResturant implements java.io.Serializable {

	private IngredientJoinItemResturantId id;
	private Ingredient ingredient;
	private ItemJoinStore itemJoinStore;
	private double addionalPrice;

	public IngredientJoinItemResturant() {
	}

	public IngredientJoinItemResturant(IngredientJoinItemResturantId id, Ingredient ingredient,
			ItemJoinStore itemJoinStore, double addionalPrice) {
		this.id = id;
		this.ingredient = ingredient;
		this.itemJoinStore = itemJoinStore;
		this.addionalPrice = addionalPrice;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ingredientId", column = @Column(name = "ingredient_id", nullable = false)),
			@AttributeOverride(name = "itemJoinStoreId", column = @Column(name = "item_join_store_id", nullable = false)) })
	public IngredientJoinItemResturantId getId() {
		return this.id;
	}

	public void setId(IngredientJoinItemResturantId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ingredient_id", nullable = false, insertable = false, updatable = false)
	public Ingredient getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(Ingredient ingredient) {
		this.ingredient = ingredient;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_join_store_id", nullable = false, insertable = false, updatable = false)
	public ItemJoinStore getItemJoinStore() {
		return this.itemJoinStore;
	}

	public void setItemJoinStore(ItemJoinStore itemJoinStore) {
		this.itemJoinStore = itemJoinStore;
	}

	@Column(name = "addional_price", nullable = false, precision = 22, scale = 0)
	public double getAddionalPrice() {
		return this.addionalPrice;
	}

	public void setAddionalPrice(double addionalPrice) {
		this.addionalPrice = addionalPrice;
	}

}
