package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemOption generated by hbm2java
 */
@Entity
@Table(name = "item_option", catalog = "traveldb")
public class ItemOption implements java.io.Serializable {

	private Integer itemOptionId;
	private String optionName;
	private Set<OptionJoinItem> optionJoinItems = new HashSet<OptionJoinItem>(0);

	public ItemOption() {
	}

	public ItemOption(String optionName) {
		this.optionName = optionName;
	}

	public ItemOption(String optionName, Set<OptionJoinItem> optionJoinItems) {
		this.optionName = optionName;
		this.optionJoinItems = optionJoinItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "item_option_id", unique = true, nullable = false)
	public Integer getItemOptionId() {
		return this.itemOptionId;
	}

	public void setItemOptionId(Integer itemOptionId) {
		this.itemOptionId = itemOptionId;
	}

	@Column(name = "option_name", nullable = false, length = 100)
	public String getOptionName() {
		return this.optionName;
	}

	public void setOptionName(String optionName) {
		this.optionName = optionName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "itemOption")
	public Set<OptionJoinItem> getOptionJoinItems() {
		return this.optionJoinItems;
	}

	public void setOptionJoinItems(Set<OptionJoinItem> optionJoinItems) {
		this.optionJoinItems = optionJoinItems;
	}

}
