package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "traveldb")
public class Item implements java.io.Serializable {

	private Integer itemId;
	private String itemOriginalName;
	private Set<ItemJoinLanguage> itemJoinLanguages = new HashSet<ItemJoinLanguage>(0);
	private Set<Type> types = new HashSet<Type>(0);
	private Set<ItemJoinStore> itemJoinStores = new HashSet<ItemJoinStore>(0);

	public Item() {
	}

	public Item(String itemOriginalName) {
		this.itemOriginalName = itemOriginalName;
	}

	public Item(String itemOriginalName, Set<ItemJoinLanguage> itemJoinLanguages, Set<Type> types,
			Set<ItemJoinStore> itemJoinStores) {
		this.itemOriginalName = itemOriginalName;
		this.itemJoinLanguages = itemJoinLanguages;
		this.types = types;
		this.itemJoinStores = itemJoinStores;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "item_id", unique = true, nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@Column(name = "Item_original_name", nullable = false, length = 300)
	public String getItemOriginalName() {
		return this.itemOriginalName;
	}

	public void setItemOriginalName(String itemOriginalName) {
		this.itemOriginalName = itemOriginalName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<ItemJoinLanguage> getItemJoinLanguages() {
		return this.itemJoinLanguages;
	}

	public void setItemJoinLanguages(Set<ItemJoinLanguage> itemJoinLanguages) {
		this.itemJoinLanguages = itemJoinLanguages;
	}

	@ManyToMany(cascade=CascadeType.ALL, mappedBy = "items")
	public Set<Type> getTypes() {
		return this.types;
	}

	public void setTypes(Set<Type> types) {
		this.types = types;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "item")
	public Set<ItemJoinStore> getItemJoinStores() {
		return this.itemJoinStores;
	}

	public void setItemJoinStores(Set<ItemJoinStore> itemJoinStores) {
		this.itemJoinStores = itemJoinStores;
	}

}
