package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemImage generated by hbm2java
 */
@Entity
@Table(name = "item_image", catalog = "traveldb")
public class ItemImage implements java.io.Serializable {

	private Integer itemImageId;
	private ItemJoinStore itemJoinStore;
	private String imageName;

	public ItemImage() {
	}

	public ItemImage(ItemJoinStore itemJoinStore) {
		this.itemJoinStore = itemJoinStore;
	}

	public ItemImage(ItemJoinStore itemJoinStore, String imageName) {
		this.itemJoinStore = itemJoinStore;
		this.imageName = imageName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "item_image_id", unique = true, nullable = false)
	public Integer getItemImageId() {
		return this.itemImageId;
	}

	public void setItemImageId(Integer itemImageId) {
		this.itemImageId = itemImageId;
	}

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "item_join_store_id", nullable = false)
	public ItemJoinStore getItemJoinStore() {
		return this.itemJoinStore;
	}

	public void setItemJoinStore(ItemJoinStore itemJoinStore) {
		this.itemJoinStore = itemJoinStore;
	}

	@Column(name = "image_name", length = 20)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

}
