package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemJoinLanguage generated by hbm2java
 */
@Entity
@Table(name = "item_join_language", catalog = "traveldb")
public class ItemJoinLanguage implements java.io.Serializable {

	private ItemJoinLanguageId id;
	private Item item;
	private Language language;
	private String itemName;
	private String itemDescription;

	public ItemJoinLanguage() {
	}

	public ItemJoinLanguage(ItemJoinLanguageId id, Item item, Language language, String itemName,
			String itemDescription) {
		this.id = id;
		this.item = item;
		this.language = language;
		this.itemName = itemName;
		this.itemDescription = itemDescription;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public ItemJoinLanguageId getId() {
		return this.id;
	}

	public void setId(ItemJoinLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false, insertable = false, updatable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "item_name", nullable = false, length = 1000)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_description", nullable = false, length = 5000)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

}
