package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", catalog = "traveldb")
public class Language implements java.io.Serializable {

	private Integer languageId;
	private String name;
	private String code;
	private Set<LanguageJoinGroup> languageJoinGroups = new HashSet<LanguageJoinGroup>(0);
	private Set<ItemJoinLanguage> itemJoinLanguages = new HashSet<ItemJoinLanguage>(0);
	private Set<TypeJoinLanguage> typeJoinLanguages = new HashSet<TypeJoinLanguage>(0);
	private Set<ShopJoinLanguage> shopJoinLanguages = new HashSet<ShopJoinLanguage>(0);

	public Language() {
	}

	public Language(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public Language(String name, String code, Set<LanguageJoinGroup> languageJoinGroups,
			Set<ItemJoinLanguage> itemJoinLanguages, Set<TypeJoinLanguage> typeJoinLanguages,
			Set<ShopJoinLanguage> shopJoinLanguages) {
		this.name = name;
		this.code = code;
		this.languageJoinGroups = languageJoinGroups;
		this.itemJoinLanguages = itemJoinLanguages;
		this.typeJoinLanguages = typeJoinLanguages;
		this.shopJoinLanguages = shopJoinLanguages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "language_id", unique = true, nullable = false)
	public Integer getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Integer languageId) {
		this.languageId = languageId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<LanguageJoinGroup> getLanguageJoinGroups() {
		return this.languageJoinGroups;
	}

	public void setLanguageJoinGroups(Set<LanguageJoinGroup> languageJoinGroups) {
		this.languageJoinGroups = languageJoinGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<ItemJoinLanguage> getItemJoinLanguages() {
		return this.itemJoinLanguages;
	}

	public void setItemJoinLanguages(Set<ItemJoinLanguage> itemJoinLanguages) {
		this.itemJoinLanguages = itemJoinLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<TypeJoinLanguage> getTypeJoinLanguages() {
		return this.typeJoinLanguages;
	}

	public void setTypeJoinLanguages(Set<TypeJoinLanguage> typeJoinLanguages) {
		this.typeJoinLanguages = typeJoinLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<ShopJoinLanguage> getShopJoinLanguages() {
		return this.shopJoinLanguages;
	}

	public void setShopJoinLanguages(Set<ShopJoinLanguage> shopJoinLanguages) {
		this.shopJoinLanguages = shopJoinLanguages;
	}

}
