package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LanguageJoinGroup generated by hbm2java
 */
@Entity
@Table(name = "language_join_group", catalog = "traveldb")
public class LanguageJoinGroup implements java.io.Serializable {

	private LanguageJoinGroupId id;
	private FoodGroup foodGroup;
	private Language language;
	private String groupName;

	public LanguageJoinGroup() {
	}

	public LanguageJoinGroup(LanguageJoinGroupId id, FoodGroup foodGroup, Language language, String groupName) {
		this.id = id;
		this.foodGroup = foodGroup;
		this.language = language;
		this.groupName = groupName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "foodGroupId", column = @Column(name = "food_group_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public LanguageJoinGroupId getId() {
		return this.id;
	}

	public void setId(LanguageJoinGroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "food_group_id", nullable = false, insertable = false, updatable = false)
	public FoodGroup getFoodGroup() {
		return this.foodGroup;
	}

	public void setFoodGroup(FoodGroup foodGroup) {
		this.foodGroup = foodGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "group_name", nullable = false, length = 500)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
