package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LanguageJoinGroupId generated by hbm2java
 */
@Embeddable
public class LanguageJoinGroupId implements java.io.Serializable {

	private int foodGroupId;
	private int languageId;

	public LanguageJoinGroupId() {
	}

	public LanguageJoinGroupId(int foodGroupId, int languageId) {
		this.foodGroupId = foodGroupId;
		this.languageId = languageId;
	}

	@Column(name = "food_group_id", nullable = false)
	public int getFoodGroupId() {
		return this.foodGroupId;
	}

	public void setFoodGroupId(int foodGroupId) {
		this.foodGroupId = foodGroupId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LanguageJoinGroupId))
			return false;
		LanguageJoinGroupId castOther = (LanguageJoinGroupId) other;

		return (this.getFoodGroupId() == castOther.getFoodGroupId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFoodGroupId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
