package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinkJoinShop generated by hbm2java
 */
@Entity
@Table(name = "link_join_shop", catalog = "traveldb")
public class LinkJoinShop implements java.io.Serializable {

	private LinkJoinShopId id;
	private LinkType linkType;
	private Shop shop;
	private String link;

	public LinkJoinShop() {
	}

	public LinkJoinShop(LinkJoinShopId id, LinkType linkType, Shop shop, String link) {
		this.id = id;
		this.linkType = linkType;
		this.shop = shop;
		this.link = link;
	}

	@EmbeddedId

	@AttributeOverrides({ 
		    @AttributeOverride(name = "shopId", column = @Column(name = "shop_id", nullable = false)),
			@AttributeOverride(name = "linkTypeId", column = @Column(name = "link_type_id", nullable = false)) })
	public LinkJoinShopId getId() {
		return this.id;
	}

	public void setId(LinkJoinShopId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "link_type_id", nullable = false, insertable = false, updatable = false)
	public LinkType getLinkType() {
		
		return this.linkType;
	}

	public void setLinkType(LinkType linkType) {
		
		this.linkType = linkType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "shop_id", nullable = false, insertable = false, updatable = false)
	public Shop getShop() {
	
		return this.shop;
	}

	public void setShop(Shop shop) {
		
		this.shop = shop;
	}

	@Column(name = "link", nullable = false, length = 500)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
