package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LinkType generated by hbm2java
 */
@Entity
@Table(name = "link_type", catalog = "traveldb")
public class LinkType implements java.io.Serializable {

	private Integer linkTypeId;
	private String linkTypeName;
	private Set<LinkJoinShop> linkJoinShops = new HashSet<LinkJoinShop>(0);

	public LinkType() {
	}

	public LinkType(String linkTypeName) {
		this.linkTypeName = linkTypeName;
	}

	public LinkType(String linkTypeName, Set<LinkJoinShop> linkJoinShops) {
		this.linkTypeName = linkTypeName;
		this.linkJoinShops = linkJoinShops;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "link_type_id", unique = true, nullable = false)
	public Integer getLinkTypeId() {
		return this.linkTypeId;
	}

	public void setLinkTypeId(Integer linkTypeId) {
		this.linkTypeId = linkTypeId;
	}

	@Column(name = "link_type_name", nullable = false, length = 80)
	public String getLinkTypeName() {
		return this.linkTypeName;
	}

	public void setLinkTypeName(String linkTypeName) {
		this.linkTypeName = linkTypeName;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "linkType")
	public Set<LinkJoinShop> getLinkJoinShops() {
		return this.linkJoinShops;
	}

	public void setLinkJoinShops(Set<LinkJoinShop> linkJoinShops) {
		this.linkJoinShops = linkJoinShops;
	}

}
