package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkJoinShopId generated by hbm2java
 */
@Embeddable
public class LinkJoinShopId implements java.io.Serializable {

	private int shopId;
	private int linkTypeId;

	public LinkJoinShopId() {
	}

	public LinkJoinShopId(int shopId, int linkTypeId) {
		this.shopId = shopId;
		this.linkTypeId = linkTypeId;
	}

	@Column(name = "shop_id", nullable = false)
	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	@Column(name = "link_type_id", nullable = false)
	public int getLinkTypeId() {
		return this.linkTypeId;
	}

	public void setLinkTypeId(int linkTypeId) {
		this.linkTypeId = linkTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinkJoinShopId))
			return false;
		LinkJoinShopId castOther = (LinkJoinShopId) other;

		return (this.getShopId() == castOther.getShopId()) && (this.getLinkTypeId() == castOther.getLinkTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getShopId();
		result = 37 * result + this.getLinkTypeId();
		return result;
	}

}
