package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OptionJoinItemId generated by hbm2java
 */
@Embeddable
public class OptionJoinItemId implements java.io.Serializable {

	private int itemJoinStoreId;
	private int itemOptionId;

	public OptionJoinItemId() {
	}

	public OptionJoinItemId(int itemJoinStoreId, int itemOptionId) {
		this.itemJoinStoreId = itemJoinStoreId;
		this.itemOptionId = itemOptionId;
	}

	@Column(name = "item_join_store_id", nullable = false)
	public int getItemJoinStoreId() {
		return this.itemJoinStoreId;
	}

	public void setItemJoinStoreId(int itemJoinStoreId) {
		this.itemJoinStoreId = itemJoinStoreId;
	}

	@Column(name = "item_option_id", nullable = false)
	public int getItemOptionId() {
		return this.itemOptionId;
	}

	public void setItemOptionId(int itemOptionId) {
		this.itemOptionId = itemOptionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OptionJoinItemId))
			return false;
		OptionJoinItemId castOther = (OptionJoinItemId) other;

		return (this.getItemJoinStoreId() == castOther.getItemJoinStoreId())
				&& (this.getItemOptionId() == castOther.getItemOptionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItemJoinStoreId();
		result = 37 * result + this.getItemOptionId();
		return result;
	}

}
