package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OptionJoinItem generated by hbm2java
 */
@Entity
@Table(name = "option_join_item", catalog = "traveldb")
public class OptionJoinItem implements java.io.Serializable {

	private OptionJoinItemId id;
	private ItemJoinStore itemJoinStore;
	private ItemOption itemOption;
	private double price;

	public OptionJoinItem() {
	}

	public OptionJoinItem(OptionJoinItemId id, ItemJoinStore itemJoinStore, ItemOption itemOption, double price) {
		this.id = id;
		this.itemJoinStore = itemJoinStore;
		this.itemOption = itemOption;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "itemJoinStoreId", column = @Column(name = "item_join_store_id", nullable = false)),
			@AttributeOverride(name = "itemOptionId", column = @Column(name = "item_option_id", nullable = false)) })
	public OptionJoinItemId getId() {
		return this.id;
	}

	public void setId(OptionJoinItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_join_store_id", nullable = false, insertable = false, updatable = false)
	public ItemJoinStore getItemJoinStore() {
		return this.itemJoinStore;
	}

	public void setItemJoinStore(ItemJoinStore itemJoinStore) {
		this.itemJoinStore = itemJoinStore;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_option_id", nullable = false, insertable = false, updatable = false)
	public ItemOption getItemOption() {
		return this.itemOption;
	}

	public void setItemOption(ItemOption itemOption) {
		this.itemOption = itemOption;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
