package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderForm generated by hbm2java
 */
@Entity
@Table(name = "order_form", catalog = "traveldb")
public class OrderForm implements java.io.Serializable {

	private Integer orderFormId;
	private String phone;
	private String email;
	private String fullAddress;
	private String postalCode;
	private String city;
	private String notes;
	private Date deliveryDay;
	private Date deliveryTime;
	private String session;
	private Set<User> users = new HashSet<User>(0);
	private Set<OrderLine> orderLines = new HashSet<OrderLine>(0);

	public OrderForm() {
	}

	public OrderForm(String phone, String email, String fullAddress, String postalCode, String city, Date deliveryDay,
			Date deliveryTime, String session) {
		this.phone = phone;
		this.email = email;
		this.fullAddress = fullAddress;
		this.postalCode = postalCode;
		this.city = city;
		this.deliveryDay = deliveryDay;
		this.deliveryTime = deliveryTime;
		this.session = session;
	}

	public OrderForm(String phone, String email, String fullAddress, String postalCode, String city, String notes,
			Date deliveryDay, Date deliveryTime, String session, Set<User> users, Set<OrderLine> orderLines) {
		this.phone = phone;
		this.email = email;
		this.fullAddress = fullAddress;
		this.postalCode = postalCode;
		this.city = city;
		this.notes = notes;
		this.deliveryDay = deliveryDay;
		this.deliveryTime = deliveryTime;
		this.session = session;
		this.users = users;
		this.orderLines = orderLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_form_id", unique = true, nullable = false)
	public Integer getOrderFormId() {
		return this.orderFormId;
	}

	public void setOrderFormId(Integer orderFormId) {
		this.orderFormId = orderFormId;
	}

	@Column(name = "phone", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "full_Address", nullable = false, length = 500)
	public String getFullAddress() {
		return this.fullAddress;
	}

	public void setFullAddress(String fullAddress) {
		this.fullAddress = fullAddress;
	}

	@Column(name = "postal_code", nullable = false, length = 100)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "city", nullable = false, length = 200)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "notes", length = 1000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delivery_day", nullable = false, length = 10)
	public Date getDeliveryDay() {
		return this.deliveryDay;
	}

	public void setDeliveryDay(Date deliveryDay) {
		this.deliveryDay = deliveryDay;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "delivery_time", nullable = false, length = 8)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "session", nullable = false, length = 400)
	public String getSession() {
		return this.session;
	}

	public void setSession(String session) {
		this.session = session;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "orderForms")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderForm")
	public Set<OrderLine> getOrderLines() {
		return this.orderLines;
	}

	public void setOrderLines(Set<OrderLine> orderLines) {
		this.orderLines = orderLines;
	}

}
