package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderType generated by hbm2java
 */
@Entity
@Table(name = "order_type", catalog = "traveldb")
public class OrderType implements java.io.Serializable {

	private Integer orderTypeId;
	private String orderTypeName;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public OrderType() {
	}

	public OrderType(String orderTypeName) {
		this.orderTypeName = orderTypeName;
	}

	public OrderType(String orderTypeName, Set<Orders> orderses) {
		this.orderTypeName = orderTypeName;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_type_id", unique = true, nullable = false)
	public Integer getOrderTypeId() {
		return this.orderTypeId;
	}

	public void setOrderTypeId(Integer orderTypeId) {
		this.orderTypeId = orderTypeId;
	}

	@Column(name = "order_type_name", nullable = false, length = 25)
	public String getOrderTypeName() {
		return this.orderTypeName;
	}

	public void setOrderTypeName(String orderTypeName) {
		this.orderTypeName = orderTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderType")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
