package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersId generated by hbm2java
 */
@Embeddable
public class OrdersId implements java.io.Serializable {

	private int orderLineId;
	private int itemJoinStoreId;
	private int orderTypeId;

	public OrdersId() {
	}

	public OrdersId(int orderLineId, int itemJoinStoreId, int orderTypeId) {
		this.orderLineId = orderLineId;
		this.itemJoinStoreId = itemJoinStoreId;
		this.orderTypeId = orderTypeId;
	}

	@Column(name = "order_line_id", nullable = false)
	public int getOrderLineId() {
		return this.orderLineId;
	}

	public void setOrderLineId(int orderLineId) {
		this.orderLineId = orderLineId;
	}

	@Column(name = "item_join_store_id", nullable = false)
	public int getItemJoinStoreId() {
		return this.itemJoinStoreId;
	}

	public void setItemJoinStoreId(int itemJoinStoreId) {
		this.itemJoinStoreId = itemJoinStoreId;
	}

	@Column(name = "order_type_id", nullable = false)
	public int getOrderTypeId() {
		return this.orderTypeId;
	}

	public void setOrderTypeId(int orderTypeId) {
		this.orderTypeId = orderTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersId))
			return false;
		OrdersId castOther = (OrdersId) other;

		return (this.getOrderLineId() == castOther.getOrderLineId())
				&& (this.getItemJoinStoreId() == castOther.getItemJoinStoreId())
				&& (this.getOrderTypeId() == castOther.getOrderTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderLineId();
		result = 37 * result + this.getItemJoinStoreId();
		result = 37 * result + this.getOrderTypeId();
		return result;
	}

}
