package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "traveldb")
public class Orders implements java.io.Serializable {

	private OrdersId id;
	private ItemJoinStore itemJoinStore;
	private OrderLine orderLine;
	private OrderType orderType;
	private double subTotal;
	private int qty;
	private double deliverlyCost;
	private double discountRate;

	public Orders() {
	}

	public Orders(OrdersId id, ItemJoinStore itemJoinStore, OrderLine orderLine, OrderType orderType, double subTotal,
			int qty, double deliverlyCost, double discountRate) {
		this.id = id;
		this.itemJoinStore = itemJoinStore;
		this.orderLine = orderLine;
		this.orderType = orderType;
		this.subTotal = subTotal;
		this.qty = qty;
		this.deliverlyCost = deliverlyCost;
		this.discountRate = discountRate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderLineId", column = @Column(name = "order_line_id", nullable = false)),
			@AttributeOverride(name = "itemJoinStoreId", column = @Column(name = "item_join_store_id", nullable = false)),
			@AttributeOverride(name = "orderTypeId", column = @Column(name = "order_type_id", nullable = false)) })
	public OrdersId getId() {
		return this.id;
	}

	public void setId(OrdersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_join_store_id", nullable = false, insertable = false, updatable = false)
	public ItemJoinStore getItemJoinStore() {
		return this.itemJoinStore;
	}

	public void setItemJoinStore(ItemJoinStore itemJoinStore) {
		this.itemJoinStore = itemJoinStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_line_id", nullable = false, insertable = false, updatable = false)
	public OrderLine getOrderLine() {
		return this.orderLine;
	}

	public void setOrderLine(OrderLine orderLine) {
		this.orderLine = orderLine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_type_id", nullable = false, insertable = false, updatable = false)
	public OrderType getOrderType() {
		return this.orderType;
	}

	public void setOrderType(OrderType orderType) {
		this.orderType = orderType;
	}

	@Column(name = "sub_total", nullable = false, precision = 22, scale = 0)
	public double getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(double subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	@Column(name = "deliverly_cost", nullable = false, precision = 22, scale = 0)
	public double getDeliverlyCost() {
		return this.deliverlyCost;
	}

	public void setDeliverlyCost(double deliverlyCost) {
		this.deliverlyCost = deliverlyCost;
	}

	@Column(name = "discount_rate", nullable = false, precision = 22, scale = 0)
	public double getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(double discountRate) {
		this.discountRate = discountRate;
	}

}
