package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "payment_method", catalog = "traveldb")
public class PaymentMethod implements java.io.Serializable {

	private Integer paymentMethodId;
	private String paymentMethods;
	private String cardNumber;
	private String cardOwner;
	private String securityCode;
	private Date expirationDate;
	private Set<OrderLine> orderLines = new HashSet<OrderLine>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(String paymentMethods, String cardNumber, String cardOwner, String securityCode,
			Date expirationDate) {
		this.paymentMethods = paymentMethods;
		this.cardNumber = cardNumber;
		this.cardOwner = cardOwner;
		this.securityCode = securityCode;
		this.expirationDate = expirationDate;
	}

	public PaymentMethod(String paymentMethods, String cardNumber, String cardOwner, String securityCode,
			Date expirationDate, Set<OrderLine> orderLines) {
		this.paymentMethods = paymentMethods;
		this.cardNumber = cardNumber;
		this.cardOwner = cardOwner;
		this.securityCode = securityCode;
		this.expirationDate = expirationDate;
		this.orderLines = orderLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_method_id", unique = true, nullable = false)
	public Integer getPaymentMethodId() {
		return this.paymentMethodId;
	}

	public void setPaymentMethodId(Integer paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	@Column(name = "payment_methods", nullable = false, length = 100)
	public String getPaymentMethods() {
		return this.paymentMethods;
	}

	public void setPaymentMethods(String paymentMethods) {
		this.paymentMethods = paymentMethods;
	}

	@Column(name = "card_number", nullable = false, length = 100)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "card_owner", nullable = false, length = 300)
	public String getCardOwner() {
		return this.cardOwner;
	}

	public void setCardOwner(String cardOwner) {
		this.cardOwner = cardOwner;
	}

	@Column(name = "security_code", nullable = false, length = 100)
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", nullable = false, length = 10)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
	public Set<OrderLine> getOrderLines() {
		return this.orderLines;
	}

	public void setOrderLines(Set<OrderLine> orderLines) {
		this.orderLines = orderLines;
	}

}
