package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "traveldb")
public class Review implements java.io.Serializable {

	private ReviewId id;
	private ReviewMenu reviewMenu;
	private ReviewType reviewType;
	private Shop shop;
	private User user;
	private Date reviewDate;

	public Review() {
	}

	public Review(ReviewId id, ReviewMenu reviewMenu, ReviewType reviewType, Shop shop, User user, Date reviewDate) {
		this.id = id;
		this.reviewMenu = reviewMenu;
		this.reviewType = reviewType;
		this.shop = shop;
		this.user = user;
		this.reviewDate = reviewDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "shopId", column = @Column(name = "shop_id", nullable = false)),
			@AttributeOverride(name = "reviewTypeId", column = @Column(name = "review_type_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "reviewMenuId", column = @Column(name = "review_menu_id", nullable = false)) })
	public ReviewId getId() {
		return this.id;
	}

	public void setId(ReviewId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "review_menu_id", nullable = false, insertable = false, updatable = false)
	public ReviewMenu getReviewMenu() {
		return this.reviewMenu;
	}

	public void setReviewMenu(ReviewMenu reviewMenu) {
		this.reviewMenu = reviewMenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "review_type_id", nullable = false, insertable = false, updatable = false)
	public ReviewType getReviewType() {
		return this.reviewType;
	}

	public void setReviewType(ReviewType reviewType) {
		this.reviewType = reviewType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id", nullable = false, insertable = false, updatable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "review_date", nullable = false, length = 10)
	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

}
