package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReviewMenu generated by hbm2java
 */
@Entity
@Table(name = "review_menu", catalog = "traveldb")
public class ReviewMenu implements java.io.Serializable {

	private Integer reviewMenuId;
	private String menuName;
	private Set<Review> reviews = new HashSet<Review>(0);

	public ReviewMenu() {
	}

	public ReviewMenu(String menuName) {
		this.menuName = menuName;
	}

	public ReviewMenu(String menuName, Set<Review> reviews) {
		this.menuName = menuName;
		this.reviews = reviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_menu_id", unique = true, nullable = false)
	public Integer getReviewMenuId() {
		return this.reviewMenuId;
	}

	public void setReviewMenuId(Integer reviewMenuId) {
		this.reviewMenuId = reviewMenuId;
	}

	@Column(name = "menu_name", nullable = false, length = 200)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reviewMenu")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

}
