package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReviewId generated by hbm2java
 */
@Embeddable
public class ReviewId implements java.io.Serializable {

	private int shopId;
	private int reviewTypeId;
	private int userId;
	private int reviewMenuId;

	public ReviewId() {
	}

	public ReviewId(int shopId, int reviewTypeId, int userId, int reviewMenuId) {
		this.shopId = shopId;
		this.reviewTypeId = reviewTypeId;
		this.userId = userId;
		this.reviewMenuId = reviewMenuId;
	}

	@Column(name = "shop_id", nullable = false)
	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	@Column(name = "review_type_id", nullable = false)
	public int getReviewTypeId() {
		return this.reviewTypeId;
	}

	public void setReviewTypeId(int reviewTypeId) {
		this.reviewTypeId = reviewTypeId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "review_menu_id", nullable = false)
	public int getReviewMenuId() {
		return this.reviewMenuId;
	}

	public void setReviewMenuId(int reviewMenuId) {
		this.reviewMenuId = reviewMenuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReviewId))
			return false;
		ReviewId castOther = (ReviewId) other;

		return (this.getShopId() == castOther.getShopId()) && (this.getReviewTypeId() == castOther.getReviewTypeId())
				&& (this.getUserId() == castOther.getUserId())
				&& (this.getReviewMenuId() == castOther.getReviewMenuId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getShopId();
		result = 37 * result + this.getReviewTypeId();
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getReviewMenuId();
		return result;
	}

}
