package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReviewCommandId generated by hbm2java
 */
@Embeddable
public class ReviewCommandId implements java.io.Serializable {

	private int userId;
	private int itemJoinStoreId;

	public ReviewCommandId() {
	}

	public ReviewCommandId(int userId, int itemJoinStoreId) {
		this.userId = userId;
		this.itemJoinStoreId = itemJoinStoreId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "item_join_store_id", nullable = false)
	public int getItemJoinStoreId() {
		return this.itemJoinStoreId;
	}

	public void setItemJoinStoreId(int itemJoinStoreId) {
		this.itemJoinStoreId = itemJoinStoreId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReviewCommandId))
			return false;
		ReviewCommandId castOther = (ReviewCommandId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getItemJoinStoreId() == castOther.getItemJoinStoreId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getItemJoinStoreId();
		return result;
	}

}
