package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReviewType generated by hbm2java
 */
@Entity
@Table(name = "review_type", catalog = "traveldb")
public class ReviewType implements java.io.Serializable {

	private Integer reviewTypeId;
	private String reviewType;
	private double reviewValue;
	private Set<Review> reviews = new HashSet<Review>(0);

	public ReviewType() {
	}

	public ReviewType(String reviewType, double reviewValue) {
		this.reviewType = reviewType;
		this.reviewValue = reviewValue;
	}

	public ReviewType(String reviewType, double reviewValue, Set<Review> reviews) {
		this.reviewType = reviewType;
		this.reviewValue = reviewValue;
		this.reviews = reviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_type_id", unique = true, nullable = false)
	public Integer getReviewTypeId() {
		return this.reviewTypeId;
	}

	public void setReviewTypeId(Integer reviewTypeId) {
		this.reviewTypeId = reviewTypeId;
	}

	@Column(name = "review_type", nullable = false, length = 50)
	public String getReviewType() {
		return this.reviewType;
	}

	public void setReviewType(String reviewType) {
		this.reviewType = reviewType;
	}

	@Column(name = "review_value", nullable = false, precision = 22, scale = 0)
	public double getReviewValue() {
		return this.reviewValue;
	}

	public void setReviewValue(double reviewValue) {
		this.reviewValue = reviewValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reviewType")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

}
