package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReviewCommand generated by hbm2java
 */
@Entity
@Table(name = "review_command", catalog = "traveldb")
public class ReviewCommand implements java.io.Serializable {

	private ReviewCommandId id;
	private ItemJoinStore itemJoinStore;
	private User user;
	private String comment;
	private Date createDate;

	public ReviewCommand() {
	}

	public ReviewCommand(ReviewCommandId id, ItemJoinStore itemJoinStore, User user, String comment, Date createDate) {
		this.id = id;
		this.itemJoinStore = itemJoinStore;
		this.user = user;
		this.comment = comment;
		this.createDate = createDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "itemJoinStoreId", column = @Column(name = "item_join_store_id", nullable = false)) })
	public ReviewCommandId getId() {
		return this.id;
	}

	public void setId(ReviewCommandId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_join_store_id", nullable = false, insertable = false, updatable = false)
	public ItemJoinStore getItemJoinStore() {
		return this.itemJoinStore;
	}

	public void setItemJoinStore(ItemJoinStore itemJoinStore) {
		this.itemJoinStore = itemJoinStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "comment", nullable = false, length = 2000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
