package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShopMedia generated by hbm2java
 */
@Entity
@Table(name = "shop_media", catalog = "traveldb")
public class ShopMedia implements java.io.Serializable {

	private int shopMediaId;
	private Shop shop;
	private String mediaName;
	private String mediaType;

	public ShopMedia() {
	}

	public ShopMedia(int shopMediaId, Shop shop, String mediaName, String mediaType) {
		this.shopMediaId = shopMediaId;
		this.shop = shop;
		this.mediaName = mediaName;
		this.mediaType = mediaType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shop_media_id", unique = true, nullable = false)
	public int getShopMediaId() {
		return this.shopMediaId;
	}

	public void setShopMediaId(int shopMediaId) {
		this.shopMediaId = shopMediaId;
	}

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "shop_id", nullable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@Column(name = "media_name", nullable = false, length = 50)
	public String getMediaName() {
		return this.mediaName;
	}

	public void setMediaName(String mediaName) {
		this.mediaName = mediaName;
	}

	@Column(name = "media_type", nullable = false, length = 50)
	public String getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

}
