package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShopJoinLanguage generated by hbm2java
 */
@Entity
@Table(name = "shop_join_language", catalog = "traveldb")
public class ShopJoinLanguage implements java.io.Serializable {

	private ShopJoinLanguageId id;
	private Language language;
	private Shop shop;
	private String description;
	private String name;
	private String aboutUs;

	public ShopJoinLanguage() {
	}

	public ShopJoinLanguage(ShopJoinLanguageId id, Language language, Shop shop, String description, String name,
			String aboutUs) {
		this.id = id;
		this.language = language;
		this.shop = shop;
		this.description = description;
		this.name = name;
		this.aboutUs = aboutUs;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "shopId", column = @Column(name = "shop_id", nullable = false)) })
	public ShopJoinLanguageId getId() {
		return this.id;
	}

	public void setId(ShopJoinLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id", nullable = false, insertable = false, updatable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@Column(name = "description", nullable = false, length = 5000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", nullable = false, length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "about_us", nullable = false, length = 8000)
	public String getAboutUs() {
		return this.aboutUs;
	}

	public void setAboutUs(String aboutUs) {
		this.aboutUs = aboutUs;
	}

}
