package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shop generated by hbm2java
 */
@Entity
@Table(name = "shop", catalog = "traveldb")
public class Shop implements java.io.Serializable {

	private Integer shopId;
	private Admin admin;
	private String name;
	private Date createDate;
	private Set<ItemJoinStore> itemJoinStores = new HashSet<ItemJoinStore>(0);
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<ShopJoinLanguage> shopJoinLanguages = new HashSet<ShopJoinLanguage>(0);
	private Set<LinkJoinShop> linkJoinShops = new HashSet<LinkJoinShop>(0);
	private Set<TimeTable> timeTables = new HashSet<TimeTable>(0);
	private Set<ShopMedia> shopMedias = new HashSet<ShopMedia>(0);
	private Set<Address> addresses = new HashSet<Address>(0);

	public Shop() {
	}

	public Shop(Admin admin, String name, Date createDate) {
		this.admin = admin;
		this.name = name;
		this.createDate = createDate;
	}

	public Shop(Admin admin, String name, Date createDate, Set<ItemJoinStore> itemJoinStores, Set<Review> reviews,
			Set<ShopJoinLanguage> shopJoinLanguages, Set<LinkJoinShop> linkJoinShops, Set<TimeTable> timeTables,
			Set<ShopMedia> shopMedias, Set<Address> addresses) {
		this.admin = admin;
		this.name = name;
		this.createDate = createDate;
		this.itemJoinStores = itemJoinStores;
		this.reviews = reviews;
		this.shopJoinLanguages = shopJoinLanguages;
		this.linkJoinShops = linkJoinShops;
		this.timeTables = timeTables;
		this.shopMedias = shopMedias;
		this.addresses = addresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shop_id", unique = true, nullable = false)
	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "admin_id", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@Column(name = "name", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "shop")
	public Set<ItemJoinStore> getItemJoinStores() {
		return this.itemJoinStores;
	}

	public void setItemJoinStores(Set<ItemJoinStore> itemJoinStores) {
		this.itemJoinStores = itemJoinStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shop")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shop")
	public Set<ShopJoinLanguage> getShopJoinLanguages() {
		return this.shopJoinLanguages;
	}

	public void setShopJoinLanguages(Set<ShopJoinLanguage> shopJoinLanguages) {
		this.shopJoinLanguages = shopJoinLanguages;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "shop")
	public Set<LinkJoinShop> getLinkJoinShops() {
		return this.linkJoinShops;
	}

	public void setLinkJoinShops(Set<LinkJoinShop> linkJoinShops) {
		this.linkJoinShops = linkJoinShops;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "shop")
	public Set<TimeTable> getTimeTables() {
		return this.timeTables;
	}

	public void setTimeTables(Set<TimeTable> timeTables) {
		this.timeTables = timeTables;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "shop")
	public Set<ShopMedia> getShopMedias() {
		return this.shopMedias;
	}

	public void setShopMedias(Set<ShopMedia> shopMedias) {
		this.shopMedias = shopMedias;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "shop")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
