package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShopJoinLanguageId generated by hbm2java
 */
@Embeddable
public class ShopJoinLanguageId implements java.io.Serializable {

	private int languageId;
	private int shopId;

	public ShopJoinLanguageId() {
	}

	public ShopJoinLanguageId(int languageId, int shopId) {
		this.languageId = languageId;
		this.shopId = shopId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "shop_id", nullable = false)
	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopJoinLanguageId))
			return false;
		ShopJoinLanguageId castOther = (ShopJoinLanguageId) other;

		return (this.getLanguageId() == castOther.getLanguageId()) && (this.getShopId() == castOther.getShopId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLanguageId();
		result = 37 * result + this.getShopId();
		return result;
	}

}
