package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeTable generated by hbm2java
 */
@Entity
@Table(name = "time_table", catalog = "traveldb")
public class TimeTable implements java.io.Serializable {

	private TimeTableId id;
	private Day day;
	private Shop shop;
	private Date startTime;
	private Date endTime;

	public TimeTable() {
	}

	public TimeTable(TimeTableId id, Day day, Shop shop, Date startTime, Date endTime) {
		this.id = id;
		this.day = day;
		this.shop = shop;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@EmbeddedId

	@AttributeOverrides({
		    @AttributeOverride(name = "shopId", column = @Column(name = "shop_id", nullable = false)),
			@AttributeOverride(name = "dayId", column = @Column(name = "day_id", nullable = false)) 
		    })
	public TimeTableId getId() {
		return this.id;
	}

	public void setId(TimeTableId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "day_id", nullable = false, insertable = false, updatable = false)
	public Day getDay() {
		return this.day;
	}

	public void setDay(Day day) {
		this.day = day;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "shop_id", nullable = false, insertable = false, updatable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start_time", nullable = false, length = 8)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end_time", nullable = false, length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
