package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TypeJoinLanguageId generated by hbm2java
 */
@Embeddable
public class TypeJoinLanguageId implements java.io.Serializable {

	private int typeId;
	private int languageId;

	public TypeJoinLanguageId() {
	}

	public TypeJoinLanguageId(int typeId, int languageId) {
		this.typeId = typeId;
		this.languageId = languageId;
	}

	@Column(name = "type_id", nullable = false)
	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TypeJoinLanguageId))
			return false;
		TypeJoinLanguageId castOther = (TypeJoinLanguageId) other;

		return (this.getTypeId() == castOther.getTypeId()) && (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTypeId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
