package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TypeJoinLanguage generated by hbm2java
 */
@Entity
@Table(name = "type_join_language", catalog = "traveldb")
public class TypeJoinLanguage implements java.io.Serializable {

	private TypeJoinLanguageId id;
	private Language language;
	private Type type;
	private String typeName;
	private String description;

	public TypeJoinLanguage() {
	}

	public TypeJoinLanguage(TypeJoinLanguageId id, Language language, Type type, String typeName, String description) {
		this.id = id;
		this.language = language;
		this.type = type;
		this.typeName = typeName;
		this.description = description;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "typeId", column = @Column(name = "type_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public TypeJoinLanguageId getId() {
		return this.id;
	}

	public void setId(TypeJoinLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false, insertable = false, updatable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false, insertable = false, updatable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "type_name", nullable = false, length = 500)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "description", nullable = false, length = 5000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
