package com.coder.model;
// Generated Jan 23, 2020 8:11:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "traveldb")
public class Type implements java.io.Serializable {

	private Integer typeId;
	private FoodGroup foodGroup;
	private String code;
	private Date createDate;
	private Set<Item> items = new HashSet<Item>(0);
	private Set<TypeJoinLanguage> typeJoinLanguages = new HashSet<TypeJoinLanguage>(0);

	public Type() {
	}

	public Type(FoodGroup foodGroup, String code, Date createDate) {
		this.foodGroup = foodGroup;
		this.code = code;
		this.createDate = createDate;
	}

	public Type(FoodGroup foodGroup, String code, Date createDate, Set<Item> items,
			Set<TypeJoinLanguage> typeJoinLanguages) {
		this.foodGroup = foodGroup;
		this.code = code;
		this.createDate = createDate;
		this.items = items;
		this.typeJoinLanguages = typeJoinLanguages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "type_id", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "food_group_id", nullable = false)
	public FoodGroup getFoodGroup() {
		return this.foodGroup;
	}

	public void setFoodGroup(FoodGroup foodGroup) {
		this.foodGroup = foodGroup;
	}

	@Column(name = "code", nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@ManyToMany(cascade=CascadeType.ALL)
	@JoinTable(name = "type_join_item", catalog = "traveldb", joinColumns = {
			@JoinColumn(name = "type_id", nullable = false, updatable = false) },
	inverseJoinColumns = {  
			@JoinColumn(name = "item_id", nullable = false, updatable = false) })
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@OneToMany(cascade=CascadeType.ALL, mappedBy = "type")
	public Set<TypeJoinLanguage> getTypeJoinLanguages() {
		return this.typeJoinLanguages;
	}

	public void setTypeJoinLanguages(Set<TypeJoinLanguage> typeJoinLanguages) {
		this.typeJoinLanguages = typeJoinLanguages;
	}

}
